version: '3.8'

services:
  app:
    hostname: ows-app
    build: App/
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=ows-db-1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=hive
      - AI_HOST=ows-ai-1
      - AI_PORT=5000
    networks:
      ows:
          ipv4_address: 172.99.0.3
    volumes:
      - ./App:/var/www/html

  db:
    hostname: ows-db
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hive
      - MYSQL_USER=root
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/hive.sql:/docker-entrypoint-initdb.d/hive.sql
    networks:
      ows:
          ipv4_address: 172.99.0.2

  ai:
    hostname: ows-ai
    build: ./AI
    ports:
      - "5001:5000"
    networks:
      ows:
          ipv4_address: 172.99.0.4
    volumes:
      - ./AI:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

  jenkins:
    hostname: ows-jenkins
    build:
      dockerfile: Jenkins/Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKIN_PORT=8080
      - MYSQL_HOST=ows-db-1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=hive
    networks:
      - jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    
  sonarqube:
    hostname: ows-sonarqube
    build: ./SonarQube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - jenkins
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  db_data:
  jenkins-data:
  jenkins-docker-certs:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

networks:
  ows:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
          gateway: 172.99.0.1
  default:
  jenkins:
